# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#  schedule:
#    - cron: 0 3 * * 0
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [achats-consultations.banque-france.fr, demat-ampa.fr]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Install deps
      #git commit -am "Replaced apt module with simple command"  run: sudo apt install git curl jq
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Download and publish DECP (${{ matrix.platform }})
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          ./processPlatform.sh ${{ matrix.platform }}
      - name: Commit and push disponibilite-donnees.csv
        run: |
          git config user.name "GitHub actions bot"
          git config user.email "<>"
          git pull origin ${{ steps.extract_branch.outputs.branch }}
          git add disponibilite-donnees.csv
          git add plateformes.csv
          git commit -m "Update ${{ secrets.API_KEY }}"
          git push origin master
