# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: 0 3 * * 0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Install deps
      #git commit -am "Replaced apt module with simple command"  run: sudo apt install git curl jq

      - name: Download and publish DECP
        run: |
          ./download-many.sh

      - name: Push updated disponibilites-donnees.csv
        run: |
          git add disponibilite-donnees.csv
          git commit -m "Updated"
          git push origin master
